linuxdeepin/dde-polkit-agent

AuthDialog.cpp
AuthDialog.h
dde-polkit-agent.pro
libdde-auth/authagent.cpp
libdde-auth/authagent.h
libdde-auth/authdbusadapter.cpp
libdde-auth/authdbusadapter.h
libdde-auth/dbus/com.deepin.daemon.Authority.xml
libdde-auth/dbus/com.deepin.daemon.authority.Agent.xml
libdde-auth/dbus/com.deepin.daemon.authority.Transaction.xml
libdde-auth/deepinauthframework.cpp
libdde-auth/deepinauthframework.h
libdde-auth/interface/deepinauthinterface.h
libdde-auth/libdde-auth.pri
policykitlistener.cpp
policykitlistener.h

https://github.com/linuxdeepin/internal-discussion/issues/548

add fingerprint in auth dialog

---

dde-polkit-agent.pro
debian/control
policykitlistener.cpp

other platform need change pam for polkit

chore: disable deepin_auth for no deepin platform

---

AuthDialog.cpp

fix: auth faild cannot set focus again

---

CMakeLists.txt
debian/control
debian/rules
policykitlistener.cpp
tests/polkit.cc

deepin modifies polkit, but other distributions cannot apply the
changes, so add conditional compilation.
Log: 其他发行版禁用修改后的接口调用

feat: add deepin-polkit test

---

archlinux/PKGBUILD
archlinux/fix.patch

add archlinux build

---

.reuse/dep5
AuthDialog.cpp
AuthDialog.h
LICENSES/CC-BY-4.0.txt
LICENSES/CC0-1.0.txt
LICENSES/GPL-3.0-or-later.txt
accessible.h
accessibledefine.h
agent-extension-proxy.h
agent-extension.h
main.cpp
pluginmanager.cpp
pluginmanager.h
policykitlistener.cpp
policykitlistener.h
tests/polkit.cc
usersmanager.cpp
usersmanager.h

Modify project to pass the REUSE check
Log: Modify project to pass the REUSE check
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: I1309e1a1b46356a2f72257facc143f8c8540b52e

chore: adapt license and copyright

---

.tx/deepin.conf
debian/changelog

update changelog to 5.5.22
Log: update changelog to 5.5.22
Influence: 构建
Change-Id: I739fd2c11dfcb11cee5b80e84afd4e2783ed6643

chore: update changelog to 5.5.22

---

policykitlistener.cpp

Session function is is ambiguous
Log:

fix: modify build-deb failed

---

CMakeLists.txt
archlinux/PKGBUILD
debian/rules

fix: bring back option

---

debian/changelog

Log: create tag and bump version

chore: create tag

---

CMakeLists.txt
debian/control
debian/rules

chore: update debian rules

---

CMakeLists.txt
pluginmanager.cpp

This reverts commit 82ffd6475e1dff9c5c49d8e2043b34d66bea9464.
fixes linuxdeepin/developer-center#4692

Revert "feat: 密码保险箱优化"

---

debian/changelog

chore: new tag with dtk

---

debian/changelog

chore: new tag 6.0.5

---

AuthDialog.cpp
AuthDialog.h
debian/changelog

https://github.com/linuxdeepin/developer-center/issues/5910

fix: auth dialog should be immovable

---

debian/changelog

chore: bump to 6.0.8

---

debian/rules

as title
Log: as title
Bug: https://pms.uniontech.com/bug-view-289335.html

fix: uos polkit agent cannot authenticate

---

debian/changelog

chore: Bump version to 6.0.10

---

AuthDialog.cpp
debian/changelog

fix: Unable to input password on X11 environment

---

policykitlistener.cpp

chore: remove some keywords
